### ISSUE TITLE
Latest Redisson not compatible

### ISSUE THREAD

**Issue by brandonlooksdumb** [2lstudios-mc/FlamePaper#22]
Hello! 

I used to use a paid Spigot fork because they had updated the libraries for Redisson versions above 3.2.3
Today I can't use this fork anymore for some particular reasons so I switched to FlamePaper. 
Except that my API doesn't want to load because it doesn't want to work with the version of Redisson that I use (3.16.6).

Here's the stacktrace:
```
java.lang.NoSuchMethodError: 'boolean io.netty.util.internal.PlatformDependent.isOsx()'
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:42) ~[?:?]
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:185) ~[?:?]
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:137) ~[?:?]
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:30) ~[?:?]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:190) ~[?:?]
	at org.redisson.Redisson.<init>(Redisson.java:67) ~[?:?]
	at org.redisson.Redisson.create(Redisson.java:108) ~[?:?]
	at com.futurygames.api.database.redis.RedisAccess.initRedisson(RedisAccess.java:44) ~[?:?]
	at com.futurygames.api.database.redis.RedisAccess.<init>(RedisAccess.java:17) ~[?:?]
	at com.futurygames.api.database.redis.RedisAccess.init(RedisAccess.java:21) ~[?:?]
	at com.futurygames.api.FuturyAPI.onEnable(FuturyAPI.java:84) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[FlamePaper.jar:]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [FlamePaper.jar:]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [FlamePaper.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [FlamePaper.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [FlamePaper.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:394) [FlamePaper.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:358) [FlamePaper.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [FlamePaper.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [FlamePaper.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:549) [FlamePaper.jar:]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I hope to get some feedback soon, thanks in advance.
Have a nice day!

**Comment by LewUwU** [comment]
This would require a netty update, that has a high probability to break tons of plugins, what do you think? @linsaftw

**Comment by LewUwU** [comment]
> just shade (and relocate) the latest netty

? just adding more size to the jar

**Comment by sadcenter** [comment]
Redisson needs new versions of netty. The netty shaded in spigot is old and incompatible with Redisson

**Comment by sadcenter** [comment]
Updating netty in spigot can cause many problems with networking and other plugins combability as I've seen many times previously in other projects such as NachoSpigot etc.
