### ISSUE TITLE
Error when start server

### ISSUE THREAD

**Issue by Yurinann** [2lstudios-mc/FlamePaper#34]
```
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.setConsoleMode(WindowsSupport.java:60)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.setConsoleMode(WindowsTerminal.java:208)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.restore(WindowsTerminal.java:95)
        at org.bukkit.craftbukkit.libs.jline.TerminalSupport$1.run(TerminalSupport.java:52)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.runTasks(ShutdownHooks.java:66)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.access$000(ShutdownHooks.java:22)
        at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks$1.run(ShutdownHooks.java:47)
```

System version: Windows 10 x64
Java version: 1.8.0_301
FlamePaper version: b52

**Comment by madmobhunter** [comment]
Loading libraries, please wait...
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
        at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.init(WindowsTerminal.java:82)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.create(TerminalFactory.java:101)
        at org.bukkit.craftbukkit.libs.jline.TerminalFactory.get(TerminalFactory.java:158)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
        at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.<init>(ConsoleReader.java:213)
        at net.minecraft.server.v1_8_R3.MinecraftServer.<init>(MinecraftServer.java:141)
        at net.minecraft.server.v1_8_R3.DedicatedServer.<init>(DedicatedServer.java:42)
        at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:951)
        at org.bukkit.craftbukkit.Main.main(Main.java:201)

[12:13:39 INFO]: Starting minecraft server version 1.8.8

**Comment by xIsm4** [comment]
> ```
> java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
>         at org.fusesource.jansi.internal.WindowsSupport.setConsoleMode(WindowsSupport.java:60)
>         at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.setConsoleMode(WindowsTerminal.java:208)
>         at org.bukkit.craftbukkit.libs.jline.WindowsTerminal.restore(WindowsTerminal.java:95)
>         at org.bukkit.craftbukkit.libs.jline.TerminalSupport$1.run(TerminalSupport.java:52)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.runTasks(ShutdownHooks.java:66)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks.access$000(ShutdownHooks.java:22)
>         at org.bukkit.craftbukkit.libs.jline.internal.ShutdownHooks$1.run(ShutdownHooks.java:47)
> ```
> 
> System version: Windows 10 x64 Java version: 1.8.0_301 FlamePaper version: b52

Seems your terminal issue!
